### PR TITLE
add me

### PR DESCRIPTION
**Pull request by User8395**
idk how to put the background image, but here it is

image

all I need is a player rig for blender and I got the perfect one...

### CODE REVIEW

**Comment by besser435** [comment]
If you open an issue instead of a pull request I can add you.

**Comment by User8395** [comment]
Ok

**Comment by besser435** [comment]
Wait I'm sorry, I didn't see that you added yourself in the file. Will merge it soon.

**Comment by MlgEpicCar** [comment]
done and dusted

**Pull request closed without merging**
